### ISSUE TITLE
Not compatible with latest intl_translation version

### ISSUE THREAD

**Issue by Isakdl** [gocal/gsheet_to_arb#6]
Because every version of gsheet_to_arb depends on analyzer ^0.33.0-alpha.0 and intl_translation 0.17.5 depends on analyzer ^0.36.0, gsheet_to_arb is incompatible with intl_translation 0.17.5.
And because no versions of intl_translation match >0.17.5 <0.18.0, gsheet_to_arb is incompatible with intl_translation ^0.17.5.

**Comment by gocal** [comment]
All dependencies has been updated in version 0.1.1
